### ISSUE TITLE
asset not packaging. 

### ISSUE THREAD

**Issue by Heaverno** [Dmgvol/UE_Modding#4]
Great tutorial! But my UE5 wont packaged any asset that's not used in the level. What should I do?

**Comment by Heaverno** [comment]
just use it in your level. no matter how you used it, you just need the asset in the pak

**Comment by Dmgvol** [comment]
Try to assign those assets to the same chunk ID, either manually or via PrimaryAssetLabel.

<https://github.com/Dmgvol/UE_Modding/blob/main/IntermediateModding/CookingContent.md#cooking-ue5>
